---
version: 2
plan:
  project-key: CL
  key: NIV
  name: NativeLibsCommon - Increment version
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  docker:
    image: adguard/core-libs:2.4
    docker-run-arguments: [ ]
  tasks:
  - !include docker-clean.yaml
  - checkout:
      path: native-libs-common
      force-clean-build: 'false'
      description: Checkout
  - checkout:
      repository: git-scripts
      path: git-scripts
  - script:
      interpreter: SHELL
      scripts:
      - |-
        set -x

        git config user.name "Bamboo"
        git config user.email "Bamboo"

        if [ "${bamboo_custom_version}" = "none" ]; then
            bamboo_custom_version=
        fi

        case "${bamboo_repository_branch_name}" in
        master|stable-*)
            cd scripts
            ./increment_version.sh ${bamboo_custom_version} || exit 1

            cd ..
            ../git-scripts/git_kit.sh pull ${bamboo_planRepository_repositoryUrl}
            git reset
            git add conandata.yml
            git commit -m "skipci: Automatic version increment by Bamboo"
            git push

            BAMBOO_URL=$(echo ${bamboo_resultsUrl} | sed -ne 's|\(https://[^/]\+\)/.*|\1|p')
            curl -H "Authorization: Bearer ${bamboo.bambooTriggerTokenSecret}" \
                "${BAMBOO_URL}/rest/api/latest/queue/CL-NUCP" -X POST -d "executeAllStages=1"

            ;;
        esac
      working-dir: native-libs-common
      description: Increment version
  requirements:
  - adg-privileged-docker
  artifact-subscriptions: []
variables:
  custom.version: 'none'
repositories:
- core-libs/native-libs-common:
    scope: global
- git-scripts:
    scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
