---
version: 2
plan:
  project-key: CL
  key: NIV
  name: NativeLibsCommon - Increment version
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  docker:
    image: adguard/core-libs:2.1
    docker-run-arguments: [ ]
  tasks:
  - !include docker-clean.yaml
  - checkout:
      path: native-libs-common
      force-clean-build: 'false'
      description: Checkout
  - script:
      interpreter: SHELL
      scripts:
      - |-
        set -x

        [ -n "$SSH_AUTH_SOCK" ] || exec ssh-agent "$0" "$@"
        export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
        printf "%b\n" "${bamboo_sshSecretKey}" | ssh-add -
        ssh-keygen -y

        git config user.name "Bamboo"
        git config user.email "Bamboo"

        if [ "${bamboo_custom_version}" = "none" ]; then
            bamboo_custom_version=
        fi

        case "${bamboo_repository_branch_name}" in
        master|stable-*)
            cd scripts
            ./increment_version.sh ${bamboo_custom_version} || exit 1

            cd ..
            ## Unlink local repo optimizations
            rm -f .git/objects/info/alternates
            rm -f .git/packed-refs
            rm -rf .git/refs/remotes
            ## Add remote repo
            git remote set-url origin ${bamboo_planRepository_repositoryUrl}
            git fetch
            git branch --set-upstream-to=origin/${bamboo_planRepository_branchName} ${bamboo_planRepository_branchName}

            git reset
            git add conandata.yml
            git commit -m "skipci: Automatic version increment by Bamboo"
            git push

            BAMBOO_URL=$(echo ${bamboo_resultsUrl} | sed -ne 's|\(https://[^/]\+\)/.*|\1|p')
            curl -H "Authorization: Bearer ${bamboo.bambooTriggerTokenSecret}" \
                "${BAMBOO_URL}/rest/api/latest/queue/CL-NUCP" -X POST -d "executeAllStages=1"

            ;;
        esac
      working-dir: native-libs-common
      description: Increment version
  requirements:
  - adg-privileged-docker
  artifact-subscriptions: []
variables:
  custom.version: 'none'
repositories:
- core-libs/native-libs-common:
    scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
