---
version: 2
plan:
  project-key: CL
  key: NRT
  name: NativeLibsCommon - Run tests
stages:
  - Builds:
      manual: false
      final: false
      jobs:
        - Android build
Android build:
  key: AB
  docker:
    image: adguard/core-libs:2.1
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
  tasks:
    - !include docker-clean.yaml
    - checkout:
        force-clean-build: "true"
        description: Checkout Default Repository
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            exec 2>&1

            python3 -m pip install conan --upgrade

            # Clean up local cache
            conan remove -c "*"
            conan remote add --index 0 art ${bamboo.conanRepoUrl} || true

            # Use system CMake instead of NDK one
            touch local.properties
            CMAKE_DIR=$(dirname $(dirname $(which cmake)))
            echo cmake.dir=$CMAKE_DIR >> local.properties

            ./gradlew :lib:assembleRelease
        working-dir: android/NativeLibsCommon
        description: Assembles libraries
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Upload built
            conan remote login art "${bamboo_artifactoryUser}" --password "${bamboo_artifactoryPassword}"
            conan upload -r art -c "*" 1>&2
            # Clean up local cache
            conan remove -c "*"
  requirements:
    - android-docker
  artifact-subscriptions: []
repositories:
  - core-libs/native-libs-common:
      scope: global
branches:
  create: for-pull-request
  delete:
    after-deleted-days: 5
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: NativeLibsCommon - Run tests
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
