---
version: 2
plan:
  project-key: CL
  key: NRT
  name: NativeLibsCommon - Run tests
stages:
  - Builds:
      manual: false
      final: false
      jobs:
        - Win build
        - Linux build
        - Mac build
Win build:
  key: WB
  tasks:
    - checkout:
        force-clean-build: 'true'
        description: Checkout Default Repository
    - script:
        interpreter: BINSH_OR_CMDEXE
        scripts:
          - |-
            call vcvars32

            cd common

            if exist build\ rmdir /s /q build || exit /b 1
            mkdir build || exit /b 1
            cd build || exit /b 1

            cmake -DCMAKE_BUILD_TYPE=Debug ^
                -DCMAKE_C_FLAGS_DEBUG=/MT ^
                -DCMAKE_CXX_FLAGS_DEBUG=/MT ^
                -G "Visual Studio 17 2022" -A Win32 ^
                ..

            cmake --build . --target tests || exit /b 1
            ctest -D ExperimentalTest --no-compress-output || exit /b 1
        description: build 32
  final-tasks:
    - any-task:
        plugin-key: fr.cstb.bamboo.plugins.ctest.bamboo-ctest-plugin:test
        configuration:
          testFilePathPattern: '**/Testing/*/*.xml'
        description: Parse tests result
    - script:
        interpreter: SHELL
        scripts:
          - |-
            REM Upload built binaries
            conan upload -r art --all -c "*" > upload.txt 2>&1
            REM Clean up local cache
            conan remove -f '*'
            conan remove --locks
  requirements:
    - system.builder.msbuild.MSBuild v15.0 (32bit)
  artifact-subscriptions: []
Linux build:
  key: LB
  docker:
    image: adguard/core-libs:latest
    docker-run-arguments: [ ]
  tasks:
    - checkout:
        force-clean-build: 'true'
        description: Checkout Default Repository
    - script:
        interpreter: SHELL
        scripts:
          - |-
            conan remote add -i 0 art ${bamboo.conanRepoUrl} || true
        description: Add remote conan
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Clean up local cache
            conan remove -f '*'

            # Build tests
            cd common
            mkdir -p build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -GNinja \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
                ..

            ninja tests

            # Run tests
            ctest -D ExperimentalTest --no-compress-output
  final-tasks:
    - any-task:
        plugin-key: fr.cstb.bamboo.plugins.ctest.bamboo-ctest-plugin:test
        configuration:
          testFilePathPattern: '**/Testing/*/*.xml'
        description: Parse tests result
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Upload built
            conan upload -r art --all -c '*' > upload.txt 2>&1
            # Clean up local cache
            conan remove -f '*'
            # Conan remove locks
            conan remove --locks
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: []
Mac build:
  key: JOB1
  tasks:
    - checkout:
        force-clean-build: 'true'
        description: Checkout Default Repository
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Clean up local cache
            conan remove -f '*'

            # Build tests
            cd common
            mkdir -p build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -GNinja \
                -DTARGET_OS=macos \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
                ..

            ninja tests

            # Run tests
            ctest -D ExperimentalTest --no-compress-output
  final-tasks:
    - any-task:
        plugin-key: fr.cstb.bamboo.plugins.ctest.bamboo-ctest-plugin:test
        configuration:
          testFilePathPattern: '**/Testing/*/*.xml'
        description: Parse tests result
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Upload built
            conan upload -r art --all -c '*' > upload.txt 2>&1
            # Clean up local cache
            conan remove -f '*'
            # Conan remove locks
            conan remove --locks
  requirements:
    - macOS 11.0 or later
  artifact-subscriptions: []
repositories:
  - core-libs/native-libs-common:
      scope: global
branches:
  create: for-pull-request
  delete:
    after-deleted-days: 5
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: NativeLibsCommon - Run tests
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
