---
version: 2
plan:
  project-key: CL
  key: NRC
  name: NativeLibsCommon - Release conanfiles.zip
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  docker:
    image: adguard/core-libs:2.4
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        path: native-libs-common
        force-clean-build: 'false'
        description: Checkout
    - checkout:
        repository: git-scripts
        path: git-scripts
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e -x

            [ -n "$SSH_AUTH_SOCK" ] || exec ssh-agent "$0" "$@"
            export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
            printf "%b\n" "${bamboo_sshSecretKey}" | ssh-add -

            ../git-scripts/git_kit.sh pull ${bamboo_planRepository_repositoryUrl}
            
            mkdir conanfiles_build
            cd conanfiles_build
            
            ARCHIVE_NAME=conanfiles.tar.gz
            
            cp -r ../conan/profiles .
            cp -r ../conan/settings_user.yml .
            cp -r ../cmake/conan_provider.cmake .
            tar czf ${ARCHIVE_NAME} *
            
            VERSION=$(cat ../conandata.yml | grep "[0-9]*\.[0-9]*." | tail -1 | sed "s/\s*\"//" | sed "s/\"\:\s*//")
            TAG="v${VERSION}"
            
            git remote remove gh || true
            git remote add gh https://${bamboo_githubPublicRepoPassword}:@github.com/AdguardTeam/NativeLibsCommon/
            git tag -d ${TAG} || true
            git tag ${TAG}
            git push origin ${TAG}
            git push gh ${TAG}
            
            gh config set -h github.com oauth_token "${bamboo_githubPublicRepoPassword}" || exit 1
            gh release create ${TAG} ${ARCHIVE_NAME} -t "Conan files ${TAG}" -n "Make various Conan-related files available for use in other AdGuard projects."
            
            cd ..
            rm -rf conanfiles_build
        working-dir: native-libs-common
        description: Increment version
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]
variables:
  custom.version: 'none'
repositories:
  - core-libs/native-libs-common:
      scope: global
  - git-scripts:
      scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
triggers: [ ]
notifications: [ ]
labels: [ ]
other:
  concurrent-build-plugin: system-default
