---
version: 2
plan:
  project-key: CL
  key: NUCP
  name: NativeLibsCommon - Upload conan recipes
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  docker:
    image: adguard/core-libs:2.8
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout
    - checkout:
        repository: git-scripts
        path: git-scripts
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            python3 -m pip install conan --upgrade

            # Clean up local cache
            conan remove -c "*"

            conan remote add --index 0 art ${bamboo.conanRepoUrl} || true

            cp ./bamboo-specs/scripts/conan_upload_and_cleanup.sh ./scripts/

            # Export packages
            cd scripts

            python3 -m pip install -r requirements.txt
            ./export_conan.py

            ./conan_upload_and_cleanup.sh
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Clean up
            conan remove -c "*"
        description: Clean up
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: []
repositories:
  - core-libs/native-libs-common:
      scope: global
  - git-scripts:
      scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
triggers: []
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
