name: Release conanfiles

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-conanfiles:
    name: Release conanfiles.tar.gz
    # This workflow should only run in the public repository, for the private part see tag-conanfiles-release.yml
    if: github.repository == 'AdguardTeam/NativeLibsCommon'
    runs-on: ubuntu-latest
    environment: conanfiles-github
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build conanfiles archive
        id: build
        run: |
          set -e -x

          mkdir conanfiles_build
          cd conanfiles_build

          ARCHIVE_NAME=conanfiles.tar.gz

          cp -r ../conan/profiles .
          cp -r ../conan/settings_user.yml .
          cp -r ../cmake/conan_provider.cmake .
          tar czf ${ARCHIVE_NAME} *

          echo "archive=${PWD}/${ARCHIVE_NAME}" >> "$GITHUB_OUTPUT"

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e -x

          TAG="${GITHUB_REF_NAME}"

          gh release create "${TAG}" "${{ steps.build.outputs.archive }}" \
            --title "Conan files ${TAG}" \
            --notes "Make various Conan-related files available for use in other AdGuard projects."

      - name: Cleanup
        if: always()
        run: rm -rf conanfiles_build
