name: Run tests

on:
  push:
    branches:
      - master
      - 'stable-*'
      - 'dev-*'
  pull_request:
  workflow_dispatch:

jobs:
  win-build:
    name: Win build
    if: github.repository == 'AdGuardSoftwareLimited/native-libs-common'
    runs-on:
      - ephemeral
      - ephemeral-vmwin
      - registry.int.agrd.dev/windows/windows2022-github:20260528-1801
      - ephemeral-limit-memory-6144
      - ephemeral-limit-cpu-8
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          $ErrorActionPreference = 'Continue'

          & conan remote add --index 0 art ${{ vars.CONAN_REPO_URL }}

          $env:Path += ";C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools"

          dir "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools"
          dir "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\amd64"

          # 1. Define the most common Microsoft SDK directories to check first (Fast Search)
          $commonPaths = @(
              "${env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin",
              "${env:ProgramFiles(x86)}\Microsoft SDKs\Windows",
              "${env:ProgramFiles}\Microsoft Visual Studio"
          )

          Set-PSDebug -Trace 1
          & "C:\Program Files\Git\usr\bin\find.exe" C:/ -iname sn.exe -o -iname msbuild.exe

          # Save vcvars to switch between them
          $vcvars32 = cmd /c "vcvars32 & set"
          $vcvars32_64 = cmd /c "vcvarsamd64_x86 & set"
          function setvar($_) {
            if ($_ -match "=") {
              $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
            }
          }

          # Build 32-bit and 64-bit versions
          & {
            $vcvars32 | foreach { setvar $_ }
            where.exe sn
            where.exe msbuild
          }
          & {
            $vcvars32_64 | foreach { setvar $_ }
            where.exe sn
            where.exe msbuild
          }          
        shell: powershell
