name: Run tests

on:
  push:
    branches:
      - master
      - 'stable-*'
      - 'dev-*'
  pull_request:
  workflow_dispatch:

jobs:
  linux-build:
    name: Linux build
    if: github.repository == 'AdGuardSoftwareLimited/native-libs-common'
    runs-on:
      - ephemeral
      - ephemeral-linux
      - registry.int.agrd.dev/linux/corelibs-builder:20260501-2313
      - ephemeral-limit-memory-8192
      - ephemeral-limit-cpu-6
      - ephemeral-limit-disk-gb-70
    container:
      image: adguard/core-libs:2.9
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure and Build
        run: |
          set -x
          
          env
          ls -la /root

          ls -la /github/home

          mount

          cargo --locked install bindgen-cli

          rmdir /github/home
          ln -sf /root /github/home

          cargo --locked install bindgen-cli

          exit 1
          
          python3 -m pip install conan --upgrade
          conan remote add --index 0 art ${{ vars.CONAN_REPO_URL }} || true

          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -GNinja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
            -DSANITIZE=yes \
            ..
          ninja tests
          ctest -D ExperimentalTest --no-compress-output

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results-linux
          path: '**/Testing/*/*.xml'

      - name: Upload to Conan
        if: always()
        run: |
          conan remote login art "${{ secrets.ARTIFACTORY_USER }}" --password "${{ secrets.ARTIFACTORY_API_KEY }}"
          conan upload -r art -c "*" 2>&1 | grep --line-buffered "Uploading"
