name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: team-platform
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Disable workflows with private uses
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e

          gh workflow list
