name: Upload conan recipes

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - After auto-tag
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      export_script_path:
        description: 'Script name to run for exporting Conan recipes'
        type: string
        default: scripts/export_conan.sh

jobs:
  upload-conan-recipes:
    name: Upload conan recipes
    if: github.repository_owner == 'AdGuardSoftwareLimited'
    environment: conan-artifactory
    runs-on: team-corelibs
    steps:
      - name: Upload conan recipes
        uses: ./.github/actions/upload-conan-recipes
        with:
          export_script_path: ${{ inputs.export_script_path || 'scripts/export_conan.sh' }}
          conan_repo_url: ${{ vars.CONAN_REPO_URL }}
          artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
          artifactory_api_key: ${{ secrets.ARTIFACTORY_API_KEY }}
